# Metadata progetto (letti direttamente da Pandoc via --metadata-file)
title: "Piccoli esploratori sonori"
subtitle: "Scuola dell'Infanzia Lorenzo Cuneo - 2025/2026"
gruppo: "A cura di MEduLab"
documentclass: article

maestri:
  - nome: "Pietro Barale"
    ruolo: "operatore"
    qualifica: "diplomato in Musica Applicata alle immagini, Conservatorio di Santa Cecilia, Roma"
  - nome: "Giulio Romano De Mattia"
    ruolo: "operatore"
    qualifica: "diplomato in Musica Elettronica, Conservatorio di Santa Cecilia, Roma"
  - nome: "Marco Di Gasbarro"
    ruolo: "coordinatore"
    qualifica: "dottorando in Composizione e Performance Musicale, Conservatorio di Ferrara"
